discord_presence:
  ready:
    activity:
      text: with cats
      type: game
    status: online
  startup:
    activity:
      text: booting...
      type: game
    status: idle
essentials:
  command_prefix: "!"
