discord_presence:
  ready:
    activity:
      text: zoom boop!
      type: custom
    status: online
  startup:
    activity:
      text: booting...
      type: custom
    status: idle
essentials:
  bot_owners:
  - Discord user
  - Another discord user
  command_prefix: "!"
